export const HEADER_TITLE = {
  SIGNUP: 'Signup',
  SIGNIN: 'Signin',
  FORGET_PASSWORD: 'Forget Password',
  RESET_PASSWORD: 'Reset Password',
  VERIFY_EMAIL: 'Verify Email',
  LINK_EXPIRED: 'Link Expired',
  EMAIL_ACCOUNT: 'Email Account',
  EMAIL_ACCOUNTS: 'Email Accounts',
  CAMPAIGN: 'Campaign',
  CAMPAIGNS: 'Campaigns',
  COUPON: 'Coupon',
  SETTINGS: 'Settings',
  UNIBOX: 'Onebox',
  ANALYTICS: 'Analytics',
  LEAD_LIST: 'Lead List',
  PROFILE: 'Account Section',
  HOME: 'Home',
  STARTUP: 'Startup Registration',
  LEAD_FINDER: 'Lead Finder',
  WEBSITE_VISITOR: 'Website Visitor',
  INBOX_PLACEMENT: 'Inbox Placement',
  PLAN_OFFER: 'Plan Offer',
}
