export const PATH = {
  INITIAL: '/',
  WEBSITE: 'https://reachinbox.ai',
  ROADMAP: 'https://reachinbox.canny.io/',
  GUIDES: 'https://guide.reachinbox.ai/',
  HELP_CENTER: 'https://help.reachinbox.ai/en/',
  TERMS: 'https://www.reachinbox.ai/terms',
  PRIVACY_POLICY: 'https://www.reachinbox.ai/privacy',
  GOOGLE_LOGIN: '/auth/google-login',
  WORKSPACE_INVITATION: '/workspace-invitation',
  APPSUMO_SIGNIN: '/appsumo/signin',
  SIGNIN: '/signin',
  SIGNUP: '/signup',
  COUPON: '/coupon',
  PLAN_OFFER: '/plan-offer',
  VERIFY_EMAIL: '/verify-email',
  ONBOARDING: '/onboarding',
  HOME: '/home',
  EMAIL_ACCOUNTS: '/email-accounts',
  CAMPAIGNS: '/campaigns',
  CAMPAIGN: '/campaign',
  CAMPAIGN_NEW: '/campaign/new',
  CAMPAIGN_METHOD: '/campaign/method',
  UNIBOX: '/onebox',
  ANALYTICS: '/analytics',
  ADD_ACCOUNT: '/add-account',
  ACCOUNTS: '/accounts',
  ACCOUNT: '/account',
  ADD_GOOGLE_ACCOUNT: '/account/google',
  SELECT_GOOGLE_OPTION: '/account/google/options',
  SELECT_GOOGLE_CONNECTION: '/account/google/connection',
  GOOGLE_ACCOUNT_SETTINGS: '/account/google/settings',
  GOOGLE_ACCOUNT_DETAILS: '/account/google/details',
  ADD_MICROSOFT_ACCOUNT: '/account/microsoft',
  ADD_OTHER_ACCOUNT: '/account/other-provider',
  ACCOUNT_CSV_UPLOAD: '/account/csv/upload',
  ACCOUNT_IMAP: '/account/imap',
  ACCOUNT_SMTP: '/account/smtp',
  SETTINGS: '/settings',
  SETTINGS_BILLING: '/settings/billing',
  SETTINGS_ACCOUNT: '/settings/account',
  SETTINGS_WORKSPACE: '/settings/workspace',
  SETTINGS_PREFERENCES: '/settings/preferences',
  SETTINGS_INTEGRATION: '/settings/integration',
  SETTINGS_BLOCKLIST: '/settings/blocklist',
  SETTINGS_BLOCKLIST_CSV: '/settings/blocklist/csv/upload',
  SETTINGS_TEMPLATES: '/settings/templates',
  LEAD_LIST: '/lead-list',
  PROFILE: '/profile',
  LEAD_FINDER: '/lead-finder',
  LEAD_FINDER_AI: '/lead-finder/ai',
  WHITELABEL_SIGNIN: '/whitelabel-signin',
  WEBSITE_VISITOR: '/website-visitor',
  INBOX_PLACEMENT: '/inbox-placement',
  INBOX_PLACEMENT_NEW: '/inbox-placement/new',
  BUY_DOMAIN: '/buy-domains',
  BUY_DOMAIN_PREWARMED: '/buy-domains/prewarmed',
  REFUND_POLICY:
    'https://help.reachinbox.ai/en/articles/8525083-what-is-the-refund-policy',
  CUSTOM_IPS: '/custom-ips',
  ENTERPRISE_BOOKING: 'https://cal.com/team/outbox/reachinbox',
} as const;


export const getDynamicPath = (id: string | number, subsequenceId?: string | number) => {
  return {
    CAMPAIGN_ANALYTICS: `/campaign/${id}/analytics`,
    CAMPAIGN_LEADS: `/campaign/${id}/leads`,
    CAMPAIGN_LEADS_NEW: `/campaign/${id}/leads/new`,
    CAMPAIGN_SEQUENCES: `/campaign/${id}/sequences`,
    CAMPAIGN_SCHEDULE: `/campaign/${id}/schedule`,
    CAMPAIGN_OPTIONS: `/campaign/${id}/options`,
    CAMPAIGN_SUBSEQUENCES: `/campaign/${id}/subsequences`,
    SUBSEQUENCE_ANALYTICS: subsequenceId ? `/campaign/${id}/subsequences/${subsequenceId}/analytics` : '',
    SUBSEQUENCE_LEADS: subsequenceId ? `/campaign/${id}/subsequences/${subsequenceId}/leads` : '',
    SUBSEQUENCE_SEQUENCES: subsequenceId ? `/campaign/${id}/subsequences/${subsequenceId}/sequence` : '',
    SUBSEQUENCE_SCHEDULE: subsequenceId ? `/campaign/${id}/subsequences/${subsequenceId}/schedule` : '',
    SUBSEQUENCE_OPTIONS: subsequenceId ? `/campaign/${id}/subsequences/${subsequenceId}/options` : '',
    POWERED_BY: `https://www.reachinbox.ai?utm_source=custom_workspace&utm_content=${id}`,
    LEAD_LIST_NEW: `/lead-list/new/${id}`,
    LEAD_LIST_ADD_LEADS: `/lead-list/new/add-leads/${id}`,
    TEST_RESULTS: `/inbox-placement/${id}/test-results`,
    TEST_CONFIGURATION: `/inbox-placement/${id}/test-configuration`,
    TEST_DRAFT_EDIT: `/inbox-placement/${id}/draft-edit`,
  };
};
